openapi: "3.0.3"
info:
  title: "Job Application Helper API"
  description: "API for managing job offers"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
  - url: "http://127.0.0.1:8080"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /offers:
    get:
      summary: "Get all offers"
      description: "Retrieve a list of all job offers"
      responses:
        "200":
          description: "List of offers"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Offer"
    post:
      summary: "Create a new offer"
      description: "Add a new job offer to the database"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OfferInput"
      responses:
        "201":
          description: "Offer created successfully"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "integer"
  /offers/{id}:
    delete:
      summary: "Delete an offer"
      description: "Delete a job offer by ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
          description: "The ID of the offer to delete"
      responses:
        "204":
          description: "Offer deleted successfully"
        "400":
          description: "Invalid ID format"
        "404":
          description: "Offer not found"
components:
  schemas:
    Offer:
      type: "object"
      properties:
        id:
          type: "integer"
        companyName:
          type: "string"
        companyImage:
          type: "string"
        position:
          type: "string"
        description:
          type: "string"
        jobType:
          type: "string"
        agreementType:
          type: "string"
        salary:
          type: "string"
        publishDate:
          type: "string"
          format: "date"
        linkToTheOffer:
          type: "string"
          format: "uri"
    OfferInput:
      type: "object"
      required:
        - companyName
        - position
        - description
        - jobType
        - agreementType
        - salary
        - publishDate
        - linkToTheOffer
      properties:
        companyName:
          type: "string"
          example: "Tech Company"
        companyImage:
          type: "string"
          example: "https://example.com/logo.png"
        position:
          type: "string"
          example: "Senior Software Engineer"
        description:
          type: "string"
          example: "Great opportunity for experienced developers"
        jobType:
          type: "string"
          example: "Full-time"
        agreementType:
          type: "string"
          example: "B2B"
        salary:
          type: "string"
          example: "15000-20000 PLN"
        publishDate:
          type: "string"
          format: "date"
          example: "2025-12-22"
        linkToTheOffer:
          type: "string"
          format: "uri"
          example: "https://example.com/offer/123"